services:
  hub_backend_db:
    image: postgres:18.1-alpine3.23
    restart: always
    ports:
      - 5432:5432
    volumes:
     - hub_backend_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER:-admin} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin} 
      POSTGRES_DB: conform
    networks:
      - hub-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    restart: always
    networks:
      - hub-network
    ports:
      - 8082:8080
    depends_on:
      - hub_backend_db 
    volumes:
      - "./keycloak.sh:/opt/keycloak/bin/keycloak.sh"
      - "./exports:/opt/keycloak/data/export"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_POSTGRES_PASSWORD:-admin} 
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD:-admin} 
      KC_DB_URL: jdbc:postgresql://hub_backend_db:5432/postgres
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

networks:
  hub-network:

volumes:
  hub_backend_data:

